name: auth-proxy
resolver:
  host: 127.0.0.11
  ttl: 3s
internal_domain_name:
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: pages_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=pages_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
namespace:
services:
  album-manager:
    server:
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
    port: 443
  pages:
    server:
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
    port: 443
  resizer:
    server:
    expose_external: true
    healthecheck: false
    healthcheck_uri: /healthcheck
    server_block: true
    protocol: https
    port: 443
  uploader:
    server:
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
    port: 443
  user-manager:
    server:
    expose_external: true
    healthecheck: false
    healthcheck_uri: /v1/
    server_block: true
    protocol: https
    port: 443
  content-service:
    server:
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
    port: 443
  fake-s3:
    server:
    expose_external: true
    healthcheck: false
    server_block: true
    protocol: http
    port: 443
